idf_component_register(SRCS "main.c" "helper.cpp" "update.cpp" "General.cpp" "RelaisNG.cpp" "ButtonNG.cpp" "TemperatureSensor.cpp" "Lamps.cpp" "wifi.cpp" "web_config.cpp"
    INCLUDE_DIRS ""
    EMBED_FILES "config_page/index.html" "config_page/minimal.js" "config_page/favicon.png" "config_page/style.css")
