idf_component_register(SRCS "main.cpp" "esp32-ha-lib/Button.cpp" "esp32-ha-lib/CAN.cpp" 
    "esp32-ha-lib/THSensor.cpp" 
    "esp32-ha-lib/Device.cpp" "esp32-ha-lib/Update.cpp" "ExtensionBoard.cpp" 
    "esp32-ha-lib/PresenceSensor.cpp" "esp32-ha-lib/EEPROM.cpp" "esp32-ha-lib/eeprom.c"
    INCLUDE_DIRS "")
