M48
; DRILL file {KiCad 7.0.5} date Mon 03 Jul 2023 12:53:45 PM CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-03T12:53:45+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0846
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1004
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1280
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.1358
%
G90
G05
T1
X6.185Y-4.6374
T2
X6.285Y-4.2826
T3
X4.252Y-2.9488
X4.252Y-4.6417
X6.8898Y-2.9488
X6.8898Y-4.6417
T4
X4.6591Y-3.2294
X5.1091Y-3.2294
T5
X5.474Y-3.0571
X5.924Y-3.0571
T0
M30
